source 'https://rubygems.org'

gem 'rails', '4.1.2'
gem 'pg'
gem 'slim'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'carrierwave'
gem 'gmaps4rails'
gem 'compass-rails'
gem 'font-awesome-rails'
gem 'chosen-rails'
gem 'devise'
gem 'bootstrap3-datetimepicker-rails'
gem 'nested_form'
gem 'momentjs-rails'
gem 'bootstrap-wysihtml5-rails'
gem 'turbolinks'
gem 'spring'
gem 'sdoc'
gem 'jbuilder'
gem 'mini_magick'
gem 'simple_form'
gem 'will_paginate', '~> 3.0'
gem 'state_machine'
gem "geocoder"
gem 'gmaps4rails'


gem 'coffee-rails'
gem 'sass-rails'
gem 'uglifier'
gem 'bootstrap-sass'
